ServerEvents.tags('item',
	event => {

	let allow_items = [
		'create:stockpile_switch',
		'create:content_observer',
		'create:mechanical_arm',
		'create:rotation_speed_controller',
		'create:sequenced_gearshift',
		'create:mechanical_crafter',
		'create:elevator_pulley',
		'create:clockwork_bearing',
		'create:smart_chute',
		'create:precision_mechanism',
		'tconstruct:scorched_anvil',
		'thermal:silver_gear',
		'thermal:silver_dust',
		'thermal:silver_nugget',
		'thermal:silver_ingot',
		'thermal:raw_silver',
		'thermal:raw_silver_block',
		'thermal:deepslate_silver_ore',
		'thermal:silver_ore',
		'thermal:silver_block',
		'create:crushed_raw_silver',
		'thermal:sulfur_block',
		'thermal:deepslate_sulfur_ore',
		'thermal:sulfur_ore',
		'thermal:sulfur',
		'thermal:sulfur_dust',
		'thermal:niter_dust',
		'thermal:niter',
		'thermal:deepslate_niter_ore',
		'thermal:niter_ore',
		'thermal:niter_block',
		'tconstruct:queens_slime_nugget',
		'tconstruct:queens_slime_ingot',
		'tconstruct:queens_slime_block',
		'thermal:constantan_gear',
		'thermal:constantan_dust',
		'thermal:constantan_nugget',
		'thermal:constantan_ingot',
		'thermal:constantan_block',
		'thermal:electrum_block',
		'thermal:electrum_gear',
		'thermal:electrum_dust',
		'thermal:electrum_nugget',
		'thermal:electrum_ingot',
		'kubejs:incomplete_mechanical_arm'
	]

	event.add("mid_meadow:automation_age", allow_items)
})