JEIEvents.hideItems(event => {
	let hide_items = [
		"minecraft:allay_spawn_egg",
		"minecraft:axolotl_spawn_egg",
		"minecraft:bat_spawn_egg",
		"minecraft:bee_spawn_egg",
		"minecraft:blaze_spawn_egg",
		"minecraft:cat_spawn_egg",
		"minecraft:cave_spider_spawn_egg",
		"minecraft:chicken_spawn_egg",
		"minecraft:cod_spawn_egg",
		"minecraft:cow_spawn_egg",
		"minecraft:creeper_spawn_egg",
		"minecraft:dolphin_spawn_egg",
		"minecraft:donkey_spawn_egg",
		"minecraft:drowned_spawn_egg",
		"minecraft:elder_guardian_spawn_egg",
		"minecraft:enderman_spawn_egg",
		"minecraft:endermite_spawn_egg",
		"minecraft:evoker_spawn_egg",
		"minecraft:fox_spawn_egg",
		"minecraft:frog_spawn_egg",
		"minecraft:ghast_spawn_egg",
		"minecraft:glow_squid_spawn_egg",
		"minecraft:goat_spawn_egg",
		"minecraft:guardian_spawn_egg",
		"minecraft:hoglin_spawn_egg",
		"minecraft:horse_spawn_egg",
		"minecraft:husk_spawn_egg",
		"minecraft:llama_spawn_egg",
		"minecraft:magma_cube_spawn_egg",
		"minecraft:mooshroom_spawn_egg",
		"minecraft:mule_spawn_egg",
		"minecraft:ocelot_spawn_egg",
		"minecraft:panda_spawn_egg",
		"minecraft:parrot_spawn_egg",
		"minecraft:phantom_spawn_egg",
		"minecraft:pig_spawn_egg",
		"minecraft:piglin_spawn_egg",
		"minecraft:piglin_brute_spawn_egg",
		"minecraft:pillager_spawn_egg",
		"minecraft:polar_bear_spawn_egg",
		"minecraft:pufferfish_spawn_egg",
		"minecraft:rabbit_spawn_egg",
		"minecraft:ravager_spawn_egg",
		"minecraft:salmon_spawn_egg",
		"minecraft:sheep_spawn_egg",
		"minecraft:shulker_spawn_egg",
		"minecraft:silverfish_spawn_egg",
		"minecraft:skeleton_spawn_egg",
		"minecraft:skeleton_horse_spawn_egg",
		"minecraft:slime_spawn_egg",
		"minecraft:spider_spawn_egg",
		"minecraft:squid_spawn_egg",
		"minecraft:stray_spawn_egg",
		"minecraft:strider_spawn_egg",
		"minecraft:tadpole_spawn_egg",
		"minecraft:trader_llama_spawn_egg",
		"minecraft:tropical_fish_spawn_egg",
		"minecraft:turtle_spawn_egg",
		"minecraft:vex_spawn_egg",
		"minecraft:villager_spawn_egg",
		"minecraft:vindicator_spawn_egg",
		"minecraft:wandering_trader_spawn_egg",
		"minecraft:warden_spawn_egg",
		"minecraft:witch_spawn_egg",
		"minecraft:wither_skeleton_spawn_egg",
		"minecraft:wolf_spawn_egg",
		"minecraft:zoglin_spawn_egg",
		"minecraft:zombie_spawn_egg",
		"minecraft:zombie_horse_spawn_egg",
		"minecraft:zombie_villager_spawn_egg",
		"minecraft:zombified_piglin_spawn_egg",
		"minecraft:water",
		"minecraft:lava",
		"minecraft:milk",
		"minecraft:budding_amethyst",
		"tconstruct:creative_slot",
		"tconstruct:creative_slot",
		"thermal:fluid_tank_creative_augment",
		"thermal:rf_coil_creative_augment",
		"create:handheld_worldshaper",
		"create:creative_blaze_cake",
		"create:creative_crate",
		"create:creative_motor",
		"create:creative_fluid_tank",
		"createaddition:creative_energy",
		"tconstruct:creative_slot",
		"tconstruct:creative_slot",
        "thermal:rf_coil_augment",
        "thermal:rf_coil_xfer_augment",
        "thermal:rf_coil_storage_augment",
        "thermal:fluid_tank_augment",
        "thermal:item_filter_augment",
        "thermal:fluid_filter_augment",
        "thermal:area_radius_augment",
        "thermal:potion_amplifier_augment",
        "thermal:potion_duration_augment",
        "thermal:xp_storage_augment",
        "thermal:earth_charge",
        "thermal:phytogro",
        "thermal:compost",
        "thermal:satchel",
        "thermal:flux_drill",
        "thermal:flux_saw",
        "thermal:flux_magnet",
        "thermal:fluid_reservoir",
        "thermal:potion_infuser",
        "thermal:sawdust",
        "thermal:rich_slag",
        "thermal:coal_coke",
        "thermal:bitumen",
        "thermal:tar",
        "thermal:rosin",
        "thermal:cinnabar",
        "thermal:apatite",
        "thermal:saw_blade",
        "thermal:drill_head",
        "thermal:hazmat_fabric",
        "thermal:diving_fabric",
        "thermal:blizz_powder",
        "thermal:blizz_rod",
        "thermal:blitz_powder",
        "thermal:blitz_rod",
        "thermal:basalz_powder",
        "thermal:basalz_rod",
        "thermal:redprint",
        "thermal:xp_crystal",
        "thermal:syrup_bottle",
        "thermal:charge_bench",
        "thermal:tinker_bench",
        "thermal:device_potion_diffuser",
        "thermal:potion_quiver",
        'thermal:copper_nugget',
        'thermal:diving_boots',
        'thermal:hazmat_leggings',
        'thermal:hazmat_boots',
        'thermal:diving_helmet',
        'thermal:diving_chestplate',
        'thermal:diving_leggings',
        'tconstruct:copper_nugget',
        'thermal:rosin_block',
        'thermal:apatite_block',
        'thermal:crude_oil_bucket',
        'thermal:syrup_bucket',
        'thermal:sap_bucket',
        'thermal:creosote_bucket',
        'thermal:cinnabar_dust',
        'computercraft:computer_command',
        'tconstruct:slime_helmet',
        'tconstruct:slime_chestplate',
        'tconstruct:ender_slime_spawn_egg',
        'tconstruct:terracube_spawn_egg',
        'tconstruct:sky_slime_spawn_egg',
        'tconstruct:sky_staff',
        'tconstruct:ender_staff',
        'tconstruct:ichor_staff',
        'tconstruct:earth_staff',
        'tconstruct:slime_boots',
        'tconstruct:slime_leggings',
        'thermal:basalz_spawn_egg',
        'thermal:blizz_spawn_egg',
        'thermal:blitz_spawn_egg',
        'thermal:rf_potato',
        'thermal:wrench',
        'thermal:ice_charge',
        'thermal:lightning_charge',
        'thermal:hazmat_helmet',
        'thermal:hazmat_chestplate',
        'thermal:refined_fuel_bucket',
        'thermal:light_oil_bucket',
        'thermal:heavy_oil_bucket',
        'thermal:bitumen_block',
        'thermal:apatite_dust',
        'thermal:sawdust_block',
        'thermal:gunpowder_block',
        'createaddition:diamond_grit',
        'thermal:cinnabar_block',
        'thermal:coal_coke_block',
        'thermal:tar_block',
		/tconstruct:crafting_station/,
		/tconstruct:part_builder/,
		/tconstruct:tinker_station/,
		/tconstruct:pickaxe/,
		/tconstruct:shovel/,
		/tconstruct:sledge_hammer/,
		/tconstruct:vein_hammer/,
		/tconstruct:mattock/,
		/tconstruct:pickadze/,
		/tconstruct:excavator/,
		/tconstruct:hand_axe/,
		/tconstruct:broad_axe/,
		/tconstruct:kama/,
		/tconstruct:scythe/,
		/tconstruct:dagger/,
		/tconstruct:sword/,
		/tconstruct:cleaver/,
		/tconstruct:crossbow/,
		/tconstruct:longbow/,
		"#itemfilters:filters",
		/ftbquests:*/,
		'ad_astra:zombified_pygro_spawn_egg',
        'ad_astra:pygro_brute_spawn_egg',
        'ad_astra:mogler_spawn_egg',
        'ad_astra:zombified_mogler_spawn_egg',
        'ad_astra:sulfur_creeper_spawn_egg',
        'ad_astra:glacian_ram_spawn_egg',
        'ad_astra:lunarian_wandering_trader_spawn_egg',
        'thermal:detonator',
        'thermal:lock',
        'ad_astra:pygro_spawn_egg',
        'ad_astra:martian_raptor_spawn_egg',
        'ad_astra:star_crawler_spawn_egg',
        'ad_astra:corrupted_lunarian_spawn_egg',
        'ad_astra:lunarian_spawn_egg',
        'ad_astra:water_pump',
        'ad_astra:compressor',
        'ad_astra:coal_generator',
        'ad_astra:hammer',
	]

	event.hide(hide_items)
})

JEIEvents.addItems(event => {

	event.add([
		Item.of('tconstruct:crafting_station', '{texture:"minecraft:dark_oak_log"}'),
		Item.of('tconstruct:part_builder', '{texture:"minecraft:oak_planks"}'),
		Item.of('tconstruct:tinker_station', '{texture:"minecraft:oak_planks"}'),
		Item.of('tconstruct:kama',			'{Damage:0,tic_broken:0b,tic_materials:["tconstruct:wood","tconstruct:wood","tconstruct:wood"],tic_modifiers:[{level:3,name:"tconstruct:cultivated"},{level:1,name:"tconstruct:tilling"},{level:1,name:"tconstruct:shears"},{level:1,name:"tconstruct:harvest"}],tic_multipliers:{"tconstruct:attack_damage":0.5f},tic_persistent:{},tic_stats:{"tconstruct:attack_damage":0.5f,"tconstruct:attack_speed":1.6f,"tconstruct:durability":60.0f,"tconstruct:mining_speed":2.0f},tic_volatile_data:{abilities:1,upgrades:3}}'),
		Item.of('tconstruct:broad_axe',		'{Damage:0,tic_broken:0b,tic_materials:["tconstruct:wood","tconstruct:wood","tconstruct:wood","tconstruct:wood"],tic_modifiers:[{level:4,name:"tconstruct:cultivated"},{level:1,name:"tconstruct:stripping"}],tic_multipliers:{"tconstruct:attack_damage":1.65f,"tconstruct:durability":4.25f,"tconstruct:mining_speed":0.3f},tic_persistent:{},tic_stats:{"tconstruct:attack_damage":8.25f,"tconstruct:attack_speed":0.6f,"tconstruct:durability":255.0f,"tconstruct:mining_speed":0.6f},tic_volatile_data:{abilities:1,upgrades:2}}'),
		Item.of('tconstruct:hand_axe',		'{Damage:0,tic_broken:0b,tic_materials:["tconstruct:wood","tconstruct:wood","tconstruct:wood"],tic_modifiers:[{level:3,name:"tconstruct:cultivated"},{level:1,name:"tconstruct:stripping"}],tic_persistent:{},tic_stats:{"tconstruct:attack_damage":6.0f,"tconstruct:attack_speed":0.9f,"tconstruct:durability":60.0f,"tconstruct:mining_speed":2.0f},tic_volatile_data:{abilities:1,upgrades:3}}'),
		Item.of('tconstruct:excavator',		'{Damage:0,tic_broken:0b,tic_materials:["tconstruct:wood","tconstruct:wood","tconstruct:wood","tconstruct:wood"],tic_modifiers:[{level:4,name:"tconstruct:cultivated"},{level:2,name:"tconstruct:knockback"},{level:1,name:"tconstruct:pathing"}],tic_multipliers:{"tconstruct:attack_damage":1.2f,"tconstruct:durability":3.75f,"tconstruct:mining_speed":0.3f},tic_persistent:{},tic_stats:{"tconstruct:attack_damage":1.8000001f,"tconstruct:durability":225.0f,"tconstruct:mining_speed":0.6f},tic_volatile_data:{abilities:1,upgrades:2}}'),
		Item.of('tconstruct:pickadze',		'{Damage:0,tic_broken:0b,tic_materials:["tconstruct:wood","tconstruct:wood","tconstruct:wood"],tic_modifiers:[{level:3,name:"tconstruct:cultivated"},{level:1,name:"tconstruct:pathing"}],tic_multipliers:{"tconstruct:attack_damage":1.15f,"tconstruct:durability":1.3f,"tconstruct:mining_speed":0.75f},tic_persistent:{},tic_stats:{"tconstruct:attack_damage":0.575f,"tconstruct:attack_speed":1.3f,"tconstruct:durability":78.0f,"tconstruct:mining_speed":1.5f},tic_volatile_data:{abilities:1,upgrades:3}}'),
		Item.of('tconstruct:mattock',		'{Damage:0,tic_broken:0b,tic_materials:["tconstruct:wood","tconstruct:wood","tconstruct:wood"],tic_modifiers:[{level:3,name:"tconstruct:cultivated"},{level:1,name:"tconstruct:tilling"}],tic_multipliers:{"tconstruct:attack_damage":1.1f,"tconstruct:durability":1.25f,"tconstruct:mining_speed":1.1f},tic_persistent:{},tic_stats:{"tconstruct:attack_damage":1.6500001f,"tconstruct:attack_speed":0.9f,"tconstruct:durability":75.0f,"tconstruct:mining_speed":2.2f},tic_volatile_data:{abilities:1,upgrades:3}}'),
		Item.of('tconstruct:vein_hammer',	'{Damage:0,tic_broken:0b,tic_materials:["tconstruct:wood","tconstruct:wood","tconstruct:wood","tconstruct:wood"],tic_modifiers:[{level:4,name:"tconstruct:cultivated"},{level:2,name:"tconstruct:pierce"}],tic_multipliers:{"tconstruct:attack_damage":1.25f,"tconstruct:durability":5.0f,"tconstruct:mining_speed":0.3f},tic_persistent:{},tic_stats:{"tconstruct:attack_damage":5.0f,"tconstruct:attack_speed":0.85f,"tconstruct:durability":300.0f,"tconstruct:mining_speed":0.6f},tic_volatile_data:{abilities:1,upgrades:2}}'),
		Item.of('tconstruct:sledge_hammer',	'{Damage:0,tic_broken:0b,tic_materials:["tconstruct:wood","tconstruct:wood","tconstruct:wood","tconstruct:wood"],tic_modifiers:[{level:4,name:"tconstruct:cultivated"},{level:2,name:"tconstruct:smite"}],tic_multipliers:{"tconstruct:attack_damage":1.35f,"tconstruct:durability":4.0f,"tconstruct:mining_speed":0.4f},tic_persistent:{},tic_stats:{"tconstruct:attack_damage":4.05f,"tconstruct:attack_speed":0.75f,"tconstruct:durability":240.0f,"tconstruct:mining_speed":0.8f},tic_volatile_data:{abilities:1,upgrades:2}}'),
		Item.of('tconstruct:pickaxe',		'{Damage:0,tic_broken:0b,tic_materials:["tconstruct:wood","tconstruct:wood","tconstruct:wood"],tic_modifiers:[{level:3,name:"tconstruct:cultivated"},{level:1,name:"tconstruct:pierce"}],tic_persistent:{},tic_stats:{"tconstruct:attack_damage":1.0f,"tconstruct:attack_speed":1.2f,"tconstruct:durability":60.0f,"tconstruct:mining_speed":2.0f},tic_volatile_data:{abilities:1,upgrades:3}}'),
		Item.of('tconstruct:longbow',		'{Damage:0,tic_broken:0b,tic_materials:["tconstruct:wood","tconstruct:wood","tconstruct:wood","tconstruct:string"],tic_modifiers:[{level:3,name:"tconstruct:cultivated"},{level:1,name:"tconstruct:stringy"}],tic_multipliers:{"tconstruct:durability":1.5f},tic_persistent:{},tic_stats:{"tconstruct:durability":360.0f},tic_volatile_data:{abilities:1,upgrades:2}}'),
		Item.of('tconstruct:crossbow',		'{Damage:0,tic_broken:0b,tic_materials:["tconstruct:wood","tconstruct:wood","tconstruct:string"],tic_modifiers:[{level:2,name:"tconstruct:cultivated"},{level:1,name:"tconstruct:stringy"}],tic_multipliers:{"tconstruct:durability":2.0f},tic_persistent:{},tic_stats:{"tconstruct:durability":120.0f},tic_volatile_data:{abilities:1,upgrades:3}}'),
		Item.of('tconstruct:cleaver',		'{Damage:0,tic_broken:0b,tic_materials:["tconstruct:wood","tconstruct:wood","tconstruct:wood","tconstruct:wood"],tic_modifiers:[{level:4,name:"tconstruct:cultivated"},{level:2,name:"tconstruct:severing"},{level:1,name:"tconstruct:silky_aoe_shears"}],tic_multipliers:{"tconstruct:attack_damage":1.5f,"tconstruct:durability":3.5f,"tconstruct:mining_speed":0.25f},tic_persistent:{},tic_stats:{"tconstruct:attack_damage":4.5f,"tconstruct:durability":210.0f,"tconstruct:mining_speed":0.5f},tic_volatile_data:{abilities:1,upgrades:2}}'),
		Item.of('tconstruct:sword',			'{Damage:0,tic_broken:0b,tic_materials:["tconstruct:wood","tconstruct:wood","tconstruct:wood"],tic_modifiers:[{level:3,name:"tconstruct:cultivated"},{level:1,name:"tconstruct:silky_shears"}],tic_multipliers:{"tconstruct:durability":1.1f,"tconstruct:mining_speed":0.5f},tic_persistent:{},tic_stats:{"tconstruct:attack_damage":3.0f,"tconstruct:attack_speed":1.6f,"tconstruct:durability":66.0f},tic_volatile_data:{abilities:1,upgrades:3}}'),
		Item.of('tconstruct:dagger',		'{Damage:0,tic_broken:0b,tic_materials:["tconstruct:wood","tconstruct:wood"],tic_modifiers:[{level:2,name:"tconstruct:cultivated"},{level:1,name:"tconstruct:offhand_attack"},{level:1,name:"tconstruct:padded"},{level:1,name:"tconstruct:silky_shears"}],tic_multipliers:{"tconstruct:attack_damage":0.65f,"tconstruct:durability":0.75f,"tconstruct:mining_speed":0.75f},tic_persistent:{},tic_stats:{"tconstruct:attack_damage":1.9499999f,"tconstruct:attack_speed":2.0f,"tconstruct:block_amount":10.0f,"tconstruct:durability":45.0f,"tconstruct:mining_speed":1.5f,"tconstruct:use_item_speed":1.0f},tic_volatile_data:{abilities:1,"tconstruct:duel_wielding":1b,upgrades:3}}'),
		Item.of('tconstruct:scythe',		'{Damage:0,tic_broken:0b,tic_materials:["tconstruct:wood","tconstruct:wood","tconstruct:wood","tconstruct:wood"],tic_modifiers:[{level:4,name:"tconstruct:cultivated"},{level:1,name:"tconstruct:tilling"},{level:1,name:"tconstruct:silky_aoe_shears"},{level:1,name:"tconstruct:harvest"}],tic_multipliers:{"tconstruct:durability":2.5f,"tconstruct:mining_speed":0.45f},tic_persistent:{},tic_stats:{"tconstruct:attack_damage":1.0f,"tconstruct:attack_speed":0.7f,"tconstruct:durability":150.0f,"tconstruct:mining_speed":0.9f},tic_volatile_data:{abilities:1,upgrades:2}}'),
		'thermal:lumium_plate'
		]);
})